export const NAMES = [
  'Shubhang  Yadav',
  'Ramkrishna Godait',
  'Shubham  Patiyal',
  'vinayak',
  'Kartik Parmar',
  'Anurag Yadav',
  'Prabhat  Patro',
  'Aditya Kushwah',
  'Aditya Shukla',
  'Vikash  Gautam',
  'Ashish solanki',
  'Dhairya yadav',
  'Saksham',
  'Ayush Nayak',
  'jishnu',
  'Veer Singh',
  'Devansh  Tinker',
  'Shreyam  Singh',
  'Raj Dinesh Rathod',
  'Piyush Bhushan Sali',
  'shubh.jain',
  'shubham deshmukh',
  'kalpit mandawe',
  'Lokbhushan Nishad ',
  'Umegh Singh',
  'Hardik LOHARIA',
  'Shivam Mahure',
  'Ketan Mahure',
  'Anurag Shastrakar',
  'sagar  Pal',
  'Arnav  Modanwal',
  'Krishna Awasthy',
  'Jagdish bhavar',
  'Rituraj  Lodhi',
  'rudra   vataliya',
  'Anany Rai',
  'Pranay wasnik',
  'ujwal  sharma',
  'Tejas Sukhadia',
  'harshit  rakhyani',
  'Narayan Vishwakarma ',
  'Pulkit   Nayak ',
  'YASH  PACHAURI',
  'Harshil  Jain',
  'Veer Rajesh Chheda',
  'Ruturaj Milind Ithape',
  'Vijay Panapt',
];

export const CATEGORY_MAP = {
  Attendance: 10,
  Interaction: 2,
  ExtraOrdinaryInteraction: 5,
  ProjectMilestone: 10,
  VideoOn: 5,
  CallYmht: 5,
  ParentAshirwad: 5,
  Aarti: 5,
  Creative: 10,
  SessionContribution: 10,
};

export const ChartSampleData = {
  Attendance: {
    data: [
      { name: 'Shubhang  Yadav', value: 20 },
      { name: 'Ramkrishna Godait', value: 10 },
    ],
  },
  Interaction: {
    data: [
      { name: 'Ramkrishna Godait', value: 2 },
      { name: 'Shubhang  Yadav', value: 4 },
    ],
  },
  ExtraOrdinaryInteraction: { data: [{ name: 'Shubhang  Yadav', value: 5 }] },
  ProjectMilestone: { data: [{ name: 'Shubhang  Yadav', value: 10 }] },
  VideoOn: { data: [{ name: 'Shubhang  Yadav', value: 5 }] },
};
